# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gilbertogaspar
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: teste-tecnico-bliss
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-requests

stages:
  default:
    params:
      tableName: 'requests-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: sa-east-1
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  environment:
    DB_HOST: ${env:DB_HOST, ''}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_NAME: ${env:DB_NAME, 'postgres'}
    DB_USER: ${env:DB_USER, 'postgres'}
    DB_PASSWORD: ${env:DB_PASSWORD, ''}
    DB_SSL_REJECT_UNAUTHORIZED: ${env:DB_SSL_REJECT_UNAUTHORIZED, 'false'}
  vpc:
    securityGroupIds:
      - ${env:DB_SECURITY_GROUP_ID, ''}
    subnetIds:
      - ${env:DB_SUBNET_ID_1, ''}
      - ${env:DB_SUBNET_ID_2, ''}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
