# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gilbertogaspar
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: teste-tecnico-bliss
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-requests

plugins:
  - serverless-offline

frameworkVersion: ~4.40.0

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: sa-east-1
  environment:
    DB_HOST: ${env:DB_HOST, ''}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_NAME: ${env:DB_NAME, 'postgres'}
    DB_USER: ${env:DB_USER, 'postgres'}
    DB_PASSWORD: ${env:DB_PASSWORD, ''}
    DB_SSL: ${env:DB_SSL, 'true'}
    DB_SSL_REJECT_UNAUTHORIZED: ${env:DB_SSL_REJECT_UNAUTHORIZED, 'false'}
  vpc:
    securityGroupIds:
      - ${env:DB_SECURITY_GROUP_ID, ''}
    subnetIds:
      - ${env:DB_SUBNET_ID_1, ''}
      - ${env:DB_SUBNET_ID_2, ''}

package:
  patterns:
    - '!.serverless/**'
    - '!.git/**'
    - '!.github/**'
    - 'node_modules/**'
    - '!node_modules/serverless/**'
    - '!node_modules/serverless-offline/**'
    - '!node_modules/typescript/**'
    - '!node_modules/ts-node/**'
    - '!node_modules/@types/**'
    - handler.ts
    - src/**
    - package.json
    - package-lock.json

functions:
  healthCheck:
    handler: handler.healthCheck
    events:
      - httpApi:
          path: /
          method: get

  createRequest:
    handler: handler.createRequest
    events:
      - httpApi:
          path: /requests
          method: post

  getRequestById:
    handler: handler.getRequestById
    events:
      - httpApi:
          path: /requests/{id}
          method: get

  listRequests:
    handler: handler.listRequests
    events:
      - httpApi:
          path: /requests
          method: get

  completeRequest:
    handler: handler.completeRequest
    events:
      - httpApi:
          path: /requests/{id}/complete
          method: patch
